'use strict';
const test=require('node:test'); const assert=require('node:assert/strict');
const {ConnectionPool}=require('../lib/pool');
const {VersionedStore,ConflictError}=require('../lib/versioned-store');
const {LockManager}=require('../lib/lock-manager');
const {ReplicaSet}=require('../lib/replica');
const {ShardRouter}=require('../lib/shard-router');
const {VersionedCache}=require('../lib/cache');
const {UniqueReservation}=require('../lib/unique-reservation');
const {AtomicBusinessStore}=require('../lib/outbox');
const {BackupManager}=require('../lib/backup');
const {RegionOwnership}=require('../lib/region-owner');
const {AuditChain}=require('../lib/audit-chain');

test('pool enforces bounded ownership and reuse',async()=>{const p=new ConnectionPool({max:1,acquireTimeoutMs:100});const a=await p.acquire();const next=p.acquire();setTimeout(()=>a.release(),10);const b=await next;assert.equal(p.stats.inUse,1);b.release();assert.equal(p.stats.inUse,0);});
test('pool acquisition times out instead of growing without bound',async()=>{const p=new ConnectionPool({max:1,acquireTimeoutMs:10});const a=await p.acquire();await assert.rejects(()=>p.acquire(),/POOL_ACQUIRE_TIMEOUT/);a.release();});
test('optimistic compare-and-set rejects stale version',()=>{const s=new VersionedStore();s.seed('acct',{balance:100});const r=s.read('acct');s.compareAndSet('acct',r.version,{balance:90});assert.throws(()=>s.compareAndSet('acct',r.version,{balance:80}),e=>e instanceof ConflictError&&e.code==='VERSION_CONFLICT');});
test('snapshot transaction rejects lost update',()=>{const s=new VersionedStore();s.seed('x',{n:1});const a=s.begin();const b=s.begin();a.write('x',{n:2});b.write('x',{n:3});a.commit();assert.throws(()=>b.commit(),/WRITE_CONFLICT/);});
test('serializable transaction detects changed read dependency',()=>{const s=new VersionedStore();s.seed('a',{n:1});s.seed('b',{n:1});const t=s.begin({isolation:'serializable'});t.read('a');const other=s.begin();other.write('a',{n:2});other.commit();t.write('b',{n:2});assert.throws(()=>t.commit(),/SERIALIZATION_FAILURE/);});
test('deadlock detector finds wait-for cycle',()=>{const l=new LockManager();assert.equal(l.acquire('t1','A').acquired,true);assert.equal(l.acquire('t2','B').acquired,true);assert.equal(l.acquire('t1','B').acquired,false);const r=l.acquire('t2','A');assert.equal(r.acquired,false);assert.deepEqual(r.deadlock,['t2','t1','t2']);});
test('replica bounded-staleness read refuses insufficient frontier',()=>{const s=new VersionedStore();s.seed('k',{v:1});const rs=new ReplicaSet(s);rs.addReplica('r');rs.replicate('r',s.commitVersion);const min=s.compareAndSet('k',1,{v:2}).version;const stale=rs.read('r','k',{minVersion:min});assert.equal(stale.stale,true);rs.replicate('r');assert.deepEqual(rs.read('r','k',{minVersion:min}).value,{v:2});});
test('reshard increments routing epoch and changes ownership',()=>{const r=new ShardRouter([{start:0,end:100,shard:'A'}]);const before=r.route(75);const epoch=r.reshard({start:50,end:100,shard:'B'});assert.ok(epoch>before.epoch);assert.equal(r.route(75).shard,'B');assert.equal(r.route(25).shard,'A');});
test('cache will not serve a version older than required',()=>{const c=new VersionedCache();c.put('k',{v:1},3);assert.equal(c.get('k',{minVersion:4}),null);c.put('k',{v:2},4);assert.deepEqual(c.get('k',{minVersion:4}).value,{v:2});});
test('write-behind flush exposes optimistic conflict rather than overwriting',()=>{const s=new VersionedStore();s.seed('k',{v:1});const c=new VersionedCache();c.enqueueWrite('k',{v:2},1);s.compareAndSet('k',1,{v:9});const [r]=c.flush(s);assert.equal(r.error,'VERSION_CONFLICT');assert.deepEqual(s.read('k').value,{v:9});});
test('distributed uniqueness reservation rejects another owner',()=>{const u=new UniqueReservation();assert.equal(u.reserve('user@example.com',{owner:'s1',epoch:2}).ok,true);const r=u.reserve('user@example.com',{owner:'s2',epoch:2});assert.equal(r.ok,false);assert.equal(r.owner,'s1');});
test('business state and outbox intent are admitted together and deduped',()=>{const s=new AtomicBusinessStore();const e={id:'e1',type:'OrderPaid'};assert.equal(s.transact({businessKey:'o1',businessValue:{state:'PAID'},event:e}).duplicate,false);assert.equal(s.transact({businessKey:'o1',businessValue:{state:'PAID'},event:e}).duplicate,true);assert.equal(s.business.get('o1').state,'PAID');});
test('checksummed backup restores the same digest',()=>{const s=new VersionedStore();s.seed('a',{x:1});s.seed('b',{x:2});const b=new BackupManager();const snap=b.create(s);const restored=b.restore(snap,VersionedStore);assert.equal(restored.digest(),s.digest());snap.payload.rows[0][1].value.x=99;assert.equal(b.verify(snap),false);});
test('regional ownership epoch fences stale writer',()=>{const o=new RegionOwnership('a');const stale={region:'a',epoch:o.epoch};o.promote('b');assert.equal(o.authorize(stale),false);assert.equal(o.authorize({region:'b',epoch:o.epoch}),true);});
test('audit chain detects mutation',()=>{const a=new AuditChain();a.append('seed',{x:1});a.append('commit',{x:2});assert.equal(a.verify(),true);a.entries[0].data.x=9;assert.equal(a.verify(),false);});
