import test from 'node:test';import assert from 'node:assert/strict';import {allocate,fee,eligible,payoutKey,Ledger,reconcile} from '../src/kernel.js';
const cases=[];
cases.push(['allocation exact',()=>assert.deepEqual(allocate(10,[1,1,1]),[4,3,3])]);
cases.push(['allocation sum',()=>assert.equal(allocate(999,[5,3,2]).reduce((a,b)=>a+b,0),999)]);
cases.push(['bad total',()=>assert.throws(()=>allocate(-1,[1]))]);
cases.push(['fee zero',()=>assert.equal(fee(1000,0),0)]);
cases.push(['fee 5%',()=>assert.equal(fee(1000,500),50)]);
cases.push(['eligible',()=>assert.equal(eligible({kyc:'eligible',restricted:false,availableMinor:1,destinationVerified:true}),true)]);
cases.push(['kyc blocks',()=>assert.equal(eligible({kyc:'pending',restricted:false,availableMinor:1,destinationVerified:true}),false)]);
cases.push(['restriction blocks',()=>assert.equal(eligible({kyc:'eligible',restricted:true,availableMinor:1,destinationVerified:true}),false)]);
cases.push(['destination blocks',()=>assert.equal(eligible({kyc:'eligible',restricted:false,availableMinor:1,destinationVerified:false}),false)]);
cases.push(['key stable',()=>assert.equal(payoutKey('s1','2026-08-01'),'payout:s1:2026-08-01')]);
cases.push(['ledger balances',()=>{const l=new Ledger();l.post('a',[{side:'debit',amountMinor:9},{side:'credit',amountMinor:9}]);assert.equal(l.trial(),0)}]);
cases.push(['ledger rejects imbalance',()=>{const l=new Ledger();assert.throws(()=>l.post('a',[{side:'debit',amountMinor:9},{side:'credit',amountMinor:8}]))}]);
cases.push(['ledger idempotent id',()=>{const l=new Ledger();const p=[{side:'debit',amountMinor:9},{side:'credit',amountMinor:9}];assert.equal(l.post('a',p),l.post('a',p))}]);
cases.push(['reconcile equal',()=>assert.deepEqual(reconcile([{id:'a',amountMinor:1}],[{id:'a',amountMinor:1}]),[])]);
cases.push(['reconcile missing',()=>assert.equal(reconcile([{id:'a',amountMinor:1}],[]).length,1)]);
cases.push(['reconcile mismatch',()=>assert.equal(reconcile([{id:'a',amountMinor:1}],[{id:'a',amountMinor:2}]).length,1)]);
for(let i=0;i<7;i++)cases.push([`allocation property ${i+1}`,()=>{const x=allocate(100+i,[2+i,3,5]);assert.equal(x.reduce((a,b)=>a+b,0),100+i)}]);
for(const [name,fn] of cases)test(name,fn);
